services:
  - docker

jobs:
  include:
    - env: OCAML_VERSION=4.12.0 UNISON_VERSION=2.52.1

script:
  - docker buildx create --use
  - docker buildx build --build-arg OCAML_VERSION=$OCAML_VERSION --build-arg UNISON_VERSION=$UNISON_VERSION --platform linux/arm64/v8,linux/amd64 --tag eugenmayer/unison:$UNISON_VERSION-$OCAML_VERSION .

deploy:
  provider: script
  script: bash build_and_publish.sh
  on:
    branch: main
      
