services:
  - docker

env:
  - OCAML_VERSION=4.12.0 UNISON_VERSION=2.51.3
  - OCAML_VERSION=4.12.0 UNISON_VERSION=2.51.4_rc2

jobs:
  include:
    - name: 'default'
      script: docker build . -t eugenmayer/unison

script: docker build  --build-arg "OCAML_VERSION=$OCAML_VERSION" --build-arg "UNISON_VERSION=$UNISON_VERSION" . -t eugenmayer/unison:$UNISON_VERSION-$OCAML_VERSION
