services:
  - docker
env:
  global:
    - OCAML_VERSION=4.12.0
  jobs:
    - UNISON_VERSION=2.51.3
    - UNISON_VERSION=2.51.4_rc2
jobs:
  include:
    - name: AMD64 Image
      script: docker build . -t eugenmayer/unison:latest
      arch: amd64
      env:
        - ARCH=AMD64
        - BASE_IMAGE=alpine:3.12
    - name: ARM64 Image
      script: docker build . -t eugenmayer/unison:latest
      arch: arm64
      env:
        - ARCH=ARM64
        - BASE_IMAGE=arm64v8/alpine:3.12
  allow_failures:
    # yet arm builds are option
    - env: ARCH=ARM64

script: docker build --build-arg "BASE_IMAGE=$BASE_IMAGE" --build-arg "OCAML_VERSION=$OCAML_VERSION" --build-arg "UNISON_VERSION=$UNISON_VERSION"
  . -t eugenmayer/unison:$UNISON_VERSION-$OCAML_VERSION-$ARCH

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
