services:
  - docker

jobs:
  include:
    - name: default
      script: docker build . -t eugenmayer/unison:latest
    - env: BASE_IMAGE=alpine:3.12 OCAML_VERSION=4.12.0 UNISON_VERSION=2.51.3
      arch: amd64
    - env: BASE_IMAGE=alpine:3.12 OCAML_VERSION=4.12.0 UNISON_VERSION=2.51.4_rc2
      arch: amd64
    - env: BASE_IMAGE=arm64v8/alpine:3.12 OCAML_VERSION=4.12.0 UNISON_VERSION=2.51.3
      arch: arm64
    - env: BASE_IMAGE=arm64v8/alpine:3.12 OCAML_VERSION=4.12.0 UNISON_VERSION=2.51.4_rc2
      arch: arm64
  allow_failures:
    # yet arm builds are option
    - arch: arm64

script: docker build
    --build-arg BASE_IMAGE=$BASE_IMAGE
    --build-arg OCAML_VERSION=$OCAML_VERSION
    --build-arg UNISON_VERSION=$UNISON_VERSION
    --tag eugenmayer/unison:$UNISON_VERSION-$OCAML_VERSION-${TRAVIS_CPU_ARCH^^}
    .

deploy:
  - provider: script
    script: bash docker_push.sh
    on:
      branch: master
  - provider: script
    script: bash docker_combine.sh
    on:
      branch: master
      arch: amd64  # only run once per OCAML/UNISON combination
